-- 初始化主键表
INSERT INTO PK_TABLE VALUES ('systemId', 100);
INSERT INTO PK_TABLE VALUES ('moduleId', 100);
INSERT INTO PK_TABLE VALUES ('monitorObjectTypeId', 100);
INSERT INTO PK_TABLE VALUES ('monitorObjectId', 100);
INSERT INTO PK_TABLE VALUES ('monitorObjectItemId', 100);
INSERT INTO PK_TABLE VALUES ('monitorInfoId', 100);
INSERT INTO PK_TABLE VALUES ('monitorItemTypeId', 100);
INSERT INTO PK_TABLE VALUES ('monitorItemId', 100);
INSERT INTO PK_TABLE VALUES ('monitorItemPropsId', 100);
INSERT INTO PK_TABLE VALUES ('alarmPersonId', 100);
INSERT INTO PK_TABLE VALUES ('alarmGroupId', 100);
INSERT INTO PK_TABLE VALUES ('alarmGroupPersonId', 100);
INSERT INTO PK_TABLE VALUES ('alarmInfoId', 100);
INSERT INTO PK_TABLE VALUES ('alarmItemGroupId', 100);
-- 初始化监控对象类型
INSERT INTO MONITOR_OBJECT_TYPE (ID, NAME, STATUS, CANCEL_FLAG, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
VALUES ('1', '服务器', 1, 0, 'admin', sysdate, 'admin', sysdate);
INSERT INTO MONITOR_OBJECT_TYPE (ID, NAME, STATUS, CANCEL_FLAG, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
VALUES ('2', '数据库', 1, 0, 'admin', sysdate, 'admin', sysdate);
INSERT INTO MONITOR_OBJECT_TYPE (ID, NAME, STATUS, CANCEL_FLAG, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
VALUES ('3', '应用程序', 1, 0, 'admin', sysdate, 'admin', sysdate);
-- 初始化监控项类型
INSERT INTO MONITOR_ITEM_TYPE (ID, NAME, STATUS, CANCEL_FLAG, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
VALUES ('1', '系统监控', 1, 0, 'admin', sysdate, 'admin', sysdate);
INSERT INTO MONITOR_ITEM_TYPE (ID, NAME, STATUS, CANCEL_FLAG, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
VALUES ('2', '应用监控', 1, 0, 'admin', sysdate, 'admin', sysdate);
